from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier, NearestCentroid
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier


def full_classifier_list(vectorizors, *args):
    return [
        (make_pipeline(*vectorizors(*args), SVC()), f'SVM kernel=rbf'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='linear')), f'SVM linear'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly')), f'SVM kernel=poly'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly', coef0=0.75)),
         f'SVM kernel=poly coef0={0.75}'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly', degree=5)),
         f'SVM kernel=poly degree=5'),
        (make_pipeline(*vectorizors(*args), SVC(degree=5, coef0=0.75, C=10)),
         f'SVM kernel=rbf, degree=5, coef0=0.75, C=10'),
        (make_pipeline(*vectorizors(*args), SVC(degree=5, coef0=0.2)),
         f'SVM kernel=rbf, degree=5, coef0=0.2'),
        (make_pipeline(*vectorizors(*args), SVC(gamma=1)),
         f'SVM kernel=rbf, gamma=1'),
        (make_pipeline(*vectorizors(*args), SVC(gamma=1, C=10)),
         f'SVM kernel=rbf, gamma=1, C=10'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly', degree=4, coef0=0.75)),
         f'SVM kernel=poly, degree=4, coef0=0.75'),
        (make_pipeline(*vectorizors(*args),
                       SVC(kernel='poly', degree=4, coef0=0.7, gamma=1, C=0.1)),
         f'SVM kernel=poly, degree=4, coef0=0.7, gamma=1, C=0.1'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly', degree=5, coef0=0.65)),
         f'SVM kernel=poly, degree=5, coef0=0.65'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly', degree=5, coef0=0.75)),
         f'SVM kernel=poly degree=5, coef0=0.75'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly', degree=4, coef0=0.75)),
         f'SVM kernel=poly degree=4, coef0=0.75'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly', degree=5, coef0=0.75)),
         f'SVM kernel=poly degree=5 coef0={0.75}'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly', degree=6)),
         f'SVM kernel=poly degree=6'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly', degree=6, coef0=0.75)),
         f'SVM kernel=poly degree=6 coef0={0.75}'),
        (make_pipeline(*vectorizors(*args), DecisionTreeClassifier()), 'DecisionTree'),
        (make_pipeline(*vectorizors(*args), LogisticRegression(max_iter=1000)),
         'LogisticRegression'),
        (make_pipeline(*vectorizors(*args), LogisticRegression(penalty="none", max_iter=1000)),
         'LogisticRegression penalty=none'),
        (make_pipeline(*vectorizors(*args), KNeighborsClassifier()), 'KNeighbors'),
        (make_pipeline(*vectorizors(*args), KNeighborsClassifier(weights='distance')),
         'KNeighbors weights=distance'),
        (make_pipeline(*vectorizors(*args), NearestCentroid()), 'NearestCentroid'),
        (make_pipeline(*vectorizors(*args), NearestCentroid(metric='cosine')),
         'NearestCentroid metric=cosine'),
        (make_pipeline(*vectorizors(*args), AdaBoostClassifier(n_estimators=70)),
         f'AdaBoost n_estimators={70}'),
        (make_pipeline(*vectorizors(*args), MinMaxScaler(), MultinomialNB()), f'MultinomialNB'),
        # (make_pipeline(*create_vectorizors(*args), GaussianNB()), f'GaussianNB'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier()), f'RandomForest'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier(bootstrap=False)), f'RandomForest bootstrap=False'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier(max_features=None)), f'RandomForest max_features=None'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier(criterion='entropy')), f'RandomForest entropy'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier(criterion='entropy', max_features=None)),
         f'RandomForest entropy max_features=None'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier(criterion='entropy', max_features='log2')),
         f'RandomForest entropy max_features=log2'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier(criterion='entropy', bootstrap=False)),
         f'RandomForest entropy bootstrap=False'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier(criterion='entropy', max_features=None, bootstrap=False)),
         f'RandomForest entropy max_features=None bootstrap=False'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier(criterion='entropy', max_features='log2', bootstrap=False)),
         f'RandomForest entropy max_features=log2 bootstrap=False'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier(n_estimators=150, criterion='entropy', bootstrap=False)),
         f'RandomForest n_estimators=150 entropy bootstrap=False'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier(n_estimators=200, criterion='entropy', bootstrap=False)),
         f'RandomForest n_estimators=200 entropy bootstrap=False'),
        (make_pipeline(*vectorizors(*args),
                       RandomForestClassifier(n_estimators=500, criterion='entropy', bootstrap=False,
                                              max_features='log2')),
         f'RandomForest n_estimators=500, criterion=entropy, bootstrap=False, max_features=log2')
    ]


def short_classifier_list(vectorizors, *args):
    return [
        (make_pipeline(*vectorizors(*args), SVC(gamma=1, C=10)),
         f'SVM kernel=rbf, gamma=1, C=10'),
        (make_pipeline(*vectorizors(*args),
                       SVC(kernel='poly', degree=4, coef0=0.7, gamma=1, C=0.1)),
         f'SVM kernel=poly, degree=4, coef0=0.7, gamma=1, C=0.1'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly', degree=5, coef0=0.75)),
         f'SVM kernel=poly degree=5, coef0=0.75'),
        (make_pipeline(*vectorizors(*args), SVC(kernel='poly', degree=4, coef0=0.75)),
         f'SVM kernel=poly degree=4, coef0=0.75'),
        (make_pipeline(*vectorizors(*args), LogisticRegression(penalty="none", max_iter=1000)),
         'LogisticRegression penalty=none'),
        (make_pipeline(*vectorizors(*args), KNeighborsClassifier(weights='distance')),
         'KNeighbors weights=distance')
    ]